server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

warehouse:
  address:
    country: Russia
    city: Moscow
    street: ADDRESS_2
    house: "1"
    flat: "1"
